function configuration = bmmo_3600D_SP19_model_configuration()
% function configuration = bmmo_3600D_model_configuration()
%
% This function generates a bmmo_Configuration object, with the default
% bmmo model settings on a NXE:3600D (SP19 version) scanner.
%
% The configuration object is currently only used for the inline SDM model
%
% Input:
% none
%
% Output:
% configuration:  bmmo_Configuration object
%
% See also bmmo_Configuration, bmmo_3400B_model_configuration, 
% bmmo_3400C_model_configuration, bl3_3600D_model_configuration

configuration_data = {...
    'InlineSdmModel',   'Default'; ...
    'LensModel',        'Default'; ...
    'HocModel',         'Default'; ...
    'CetModel',         'VERSION_5'; ...
    'HocFilter',        '33Par'; ...
    'HocPoly2Spline',   'Disabled'; ...
    'HocPlayback',      'Enabled'; ...
	'Lens',				'3400_34'; ...
    };
    
configuration = bmmo_Configuration(configuration_data(:,1), ...
    configuration_data(:,2));

end