function parlist = bmmo_parlist
% function parlist = bmmo_parlist
%
% Generate a parameter list for BMMO/BL3
%
% This function is autogenerated by the function bmmo_generate_parlist
%
% Input: None
%
% Output: 
%  parlist: structure with one field per parameter


%                      |     dx exponents    |      dy exponents
%                      dx xf yf xc yc xw yw dy xf yf xc yc xw yw
parlist.tx.args 	= [1  0  0  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.ty.args 	= [0  0  0  0  0  0  0  1  0  0  0  0  0  0  ];
parlist.ms.args 	= [1  1  0  0  0  0  0  1  0  1  0  0  0  0  ];
parlist.ma.args 	= [1  1  0  0  0  0  0  -1  0  1  0  0  0  0  ];
parlist.rs.args 	= [-1  0  1  0  0  0  0  1  1  0  0  0  0  0  ];
parlist.ra.args 	= [-1  0  1  0  0  0  0  -1  1  0  0  0  0  0  ];
parlist.mws.args 	= [1  0  0  1  0  0  0  1  0  0  0  1  0  0  ];
parlist.mwa.args 	= [1  0  0  1  0  0  0  -1  0  0  0  1  0  0  ];
parlist.rws.args 	= [-1  0  0  0  1  0  0  1  0  0  1  0  0  0  ];
parlist.rwa.args 	= [-1  0  0  0  1  0  0  -1  0  0  1  0  0  0  ];
parlist.rswfr.args 	= [-1  0  0  0  0  0  1  1  0  0  0  0  1  0  ];
parlist.mx.args 	= [1  1  0  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.my.args 	= [0  0  0  0  0  0  0  1  0  1  0  0  0  0  ];
parlist.rx.args 	= [-1  0  1  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.ry.args 	= [0  0  0  0  0  0  0  1  1  0  0  0  0  0  ];
parlist.rwy.args 	= [0  0  0  0  0  0  0  1  0  0  0  0  1  0  ];
parlist.k5.args 	= [1  0  1  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k7.args 	= [1  2  0  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k8.args 	= [0  0  0  0  0  0  0  1  0  2  0  0  0  0  ];
parlist.k9.args 	= [1  1  1  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k10.args 	= [0  0  0  0  0  0  0  1  1  1  0  0  0  0  ];
parlist.k11.args 	= [1  0  2  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k12.args 	= [0  0  0  0  0  0  0  1  2  0  0  0  0  0  ];
parlist.k13.args 	= [1  3  0  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k14.args 	= [0  0  0  0  0  0  0  1  0  3  0  0  0  0  ];
parlist.k15.args 	= [1  2  1  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k16.args 	= [0  0  0  0  0  0  0  1  1  2  0  0  0  0  ];
parlist.k17.args 	= [1  1  2  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k18.args 	= [0  0  0  0  0  0  0  1  2  1  0  0  0  0  ];
parlist.k19.args 	= [1  0  3  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k20.args 	= [0  0  0  0  0  0  0  1  3  0  0  0  0  0  ];
parlist.k22.args 	= [0  0  0  0  0  0  0  1  0  4  0  0  0  0  ];
parlist.k24.args 	= [0  0  0  0  0  0  0  1  1  3  0  0  0  0  ];
parlist.k25.args 	= [1  2  2  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k26.args 	= [0  0  0  0  0  0  0  1  2  2  0  0  0  0  ];
parlist.k27.args 	= [1  1  3  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k29.args 	= [1  0  4  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k32.args 	= [0  0  0  0  0  0  0  1  0  5  0  0  0  0  ];
parlist.k34.args 	= [0  0  0  0  0  0  0  1  1  4  0  0  0  0  ];
parlist.k36.args 	= [0  0  0  0  0  0  0  1  2  3  0  0  0  0  ];
parlist.k37.args 	= [1  2  3  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k39.args 	= [1  1  4  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k41.args 	= [1  0  5  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.k46.args 	= [0  0  0  0  0  0  0  1  1  5  0  0  0  0  ];
parlist.k48.args 	= [0  0  0  0  0  0  0  1  2  4  0  0  0  0  ];
parlist.k51.args 	= [1  2  4  0  0  0  0  0  0  0  0  0  0  0  ];
parlist.rxwfr.args 	= [-1  0  0  0  0  0  1  0  0  0  0  0  0  0  ];
parlist.tx.dxfun = @sub_onesfun;
parlist.tx.dyfun = @sub_zerosfun;
parlist.ty.dxfun = @sub_zerosfun;
parlist.ty.dyfun = @sub_onesfun;
parlist.ms.dxfun = @sub_xffun;
parlist.ms.dyfun = @sub_yffun;
parlist.ma.dxfun = @sub_xffun;
parlist.ma.dyfun = @sub_minyffun;
parlist.rs.dxfun = @sub_minyffun;
parlist.rs.dyfun = @sub_xffun;
parlist.ra.dxfun = @sub_minyffun;
parlist.ra.dyfun = @sub_minxffun;
parlist.mws.dxfun = @sub_xcfun;
parlist.mws.dyfun = @sub_ycfun;
parlist.mwa.dxfun = @sub_xcfun;
parlist.mwa.dyfun = @sub_minycfun;
parlist.rws.dxfun = @sub_minycfun;
parlist.rws.dyfun = @sub_xcfun;
parlist.rwa.dxfun = @sub_minycfun;
parlist.rwa.dyfun = @sub_minxcfun;
parlist.rswfr.dxfun = @sub_dxfun;
parlist.rswfr.dyfun = @sub_dyfun;
parlist.mx.dxfun = @sub_dxfun;
parlist.mx.dyfun = @sub_dyfun;
parlist.my.dxfun = @sub_dxfun;
parlist.my.dyfun = @sub_dyfun;
parlist.rx.dxfun = @sub_dxfun;
parlist.rx.dyfun = @sub_dyfun;
parlist.ry.dxfun = @sub_dxfun;
parlist.ry.dyfun = @sub_dyfun;
parlist.rwy.dxfun = @sub_dxfun;
parlist.rwy.dyfun = @sub_dyfun;
parlist.k5.dxfun = @sub_dxfun;
parlist.k5.dyfun = @sub_dyfun;
parlist.k7.dxfun = @sub_dxfun;
parlist.k7.dyfun = @sub_dyfun;
parlist.k8.dxfun = @sub_dxfun;
parlist.k8.dyfun = @sub_dyfun;
parlist.k9.dxfun = @sub_dxfun;
parlist.k9.dyfun = @sub_dyfun;
parlist.k10.dxfun = @sub_dxfun;
parlist.k10.dyfun = @sub_dyfun;
parlist.k11.dxfun = @sub_dxfun;
parlist.k11.dyfun = @sub_dyfun;
parlist.k12.dxfun = @sub_dxfun;
parlist.k12.dyfun = @sub_dyfun;
parlist.k13.dxfun = @sub_dxfun;
parlist.k13.dyfun = @sub_dyfun;
parlist.k14.dxfun = @sub_dxfun;
parlist.k14.dyfun = @sub_dyfun;
parlist.k15.dxfun = @sub_dxfun;
parlist.k15.dyfun = @sub_dyfun;
parlist.k16.dxfun = @sub_dxfun;
parlist.k16.dyfun = @sub_dyfun;
parlist.k17.dxfun = @sub_dxfun;
parlist.k17.dyfun = @sub_dyfun;
parlist.k18.dxfun = @sub_dxfun;
parlist.k18.dyfun = @sub_dyfun;
parlist.k19.dxfun = @sub_dxfun;
parlist.k19.dyfun = @sub_dyfun;
parlist.k20.dxfun = @sub_dxfun;
parlist.k20.dyfun = @sub_dyfun;
parlist.k22.dxfun = @sub_dxfun;
parlist.k22.dyfun = @sub_dyfun;
parlist.k24.dxfun = @sub_dxfun;
parlist.k24.dyfun = @sub_dyfun;
parlist.k25.dxfun = @sub_dxfun;
parlist.k25.dyfun = @sub_dyfun;
parlist.k26.dxfun = @sub_dxfun;
parlist.k26.dyfun = @sub_dyfun;
parlist.k27.dxfun = @sub_dxfun;
parlist.k27.dyfun = @sub_dyfun;
parlist.k29.dxfun = @sub_dxfun;
parlist.k29.dyfun = @sub_dyfun;
parlist.k32.dxfun = @sub_dxfun;
parlist.k32.dyfun = @sub_dyfun;
parlist.k34.dxfun = @sub_dxfun;
parlist.k34.dyfun = @sub_dyfun;
parlist.k36.dxfun = @sub_dxfun;
parlist.k36.dyfun = @sub_dyfun;
parlist.k37.dxfun = @sub_dxfun;
parlist.k37.dyfun = @sub_dyfun;
parlist.k39.dxfun = @sub_dxfun;
parlist.k39.dyfun = @sub_dyfun;
parlist.k41.dxfun = @sub_dxfun;
parlist.k41.dyfun = @sub_dyfun;
parlist.k46.dxfun = @sub_dxfun;
parlist.k46.dyfun = @sub_dyfun;
parlist.k48.dxfun = @sub_dxfun;
parlist.k48.dyfun = @sub_dyfun;
parlist.k51.dxfun = @sub_dxfun;
parlist.k51.dyfun = @sub_dyfun;
parlist.rxwfr.dxfun = @sub_dxfun;
parlist.rxwfr.dyfun = @sub_dyfun;
parlist.k1 = parlist.tx;
parlist.k2 = parlist.ty;
parlist.k3 = parlist.mx;
parlist.k4 = parlist.my;
parlist.k6 = parlist.ry;
parlist.d2 = parlist.k7;
parlist.d2x = parlist.k7;
parlist.trzx = parlist.k9;
parlist.trzy = parlist.k10;
parlist.bowxf = parlist.k11;
parlist.bowyf = parlist.k12;
parlist.d2y = parlist.k12;
parlist.d3 = parlist.k13;
parlist.d3x = parlist.k13;
parlist.mag3y = parlist.k14;
parlist.accx = parlist.k15;
parlist.accy = parlist.k16;
parlist.cshpx = parlist.k17;
parlist.cshpy = parlist.k18;
parlist.flw3x = parlist.k19;
parlist.flw3y = parlist.k20;


function v = sub_dxfun(wd, args)

v = args(1) .* wd.xf.^args(2) .* wd.yf.^args(3) .* wd.xc.^args(4) .* wd.yc.^args(5) .* wd.xw.^args(6) .* wd.yw.^args(7);


function v = sub_dyfun(wd, args)

v = args(8) .* wd.xf.^args(9) .* wd.yf.^args(10) .* wd.xc.^args(11) .* wd.yc.^args(12) .* wd.xw.^args(13) .* wd.yw.^args(14);


function v = sub_zerosfun(wd, args)

v = zeros(size(wd.xf));


function v = sub_onesfun(wd, args)

v = ones(size(wd.xf));


function v = sub_xffun(wd, args)

v = wd.xf;


function v = sub_yffun(wd, args)

v = wd.yf;


function v = sub_minxffun(wd, args)

v = -wd.xf;


function v = sub_minyffun(wd, args)

v = -wd.yf;


function v = sub_xcfun(wd, args)

v = wd.xc;


function v = sub_ycfun(wd, args)

v = wd.yc;


function v = sub_minxcfun(wd, args)

v = -wd.xc;


function v = sub_minycfun(wd, args)

v = -wd.yc;
