function [mlo, options] = bmmo_process_input(input_struct)
% function [mlo, options] = bmmo_process_input(input_struct);
%
% Perform field reconstruction on the input structure and generate 
% the model options including data from its 'info' field
%
% Input:
% input_struct: Input structure as generated by bmmo_read_lcp_zip,
%               containing YieldStar measurements and all information that 
%               is needed during modeling
%
% Output:
% mlo:          model structure after field reconstruction
% options:      options structure

mlo = input_struct;

bmmo_validate_input(mlo);

if isfield(input_struct.info,'configuration_data') && isfield(input_struct.info.configuration_data,'bl3_model') && input_struct.info.configuration_data.bl3_model
    options = bl3_default_options_structure; 

    options = bl3_ml_options(mlo, options);
else
    options = bmmo_default_options_structure; 
    
    options = bmmo_ml_options(mlo, options);
end

mlo.info = rmfield(mlo.info, 'report_data'); 
mlo.info = rmfield(mlo.info, 'previous_correction');

% reconstruct to fields of 13x19 in exposure order
[mlo, options] = bmmo_field_reconstruction(mlo, options);
if strcmp(options.platform, 'LIS')
    options.model_shift.x = options.x_shift;
    options.model_shift.y = options.y_shift;
    mlo = bmmo_shift_fields(mlo, options.model_shift.x, options.model_shift.y);
end

% Initialise the wafer heating fingerprint (needs reconstructed input)
options = bmmo_wh_options(mlo, options);
